import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Kiinew",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} w-screen h-screen`}>
        <section className="flex justify-center items-center">
          <Header />
        </section>
        <section className=" overflow-x-hidden pb-[60px]">{children}</section>
      </body>
    </html>
  );
}
