import { Montserrat, Playfair } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import "react-photo-view/dist/react-photo-view.css";
import Footer from "@/components/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

const playfair = Playfair({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Kiinew",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${playfair.variable} flex flex-col min-h-screen`}
      >
        <section className="sticky w-full z-[999] flex justify-center items-center mobile:my-[0] laptop:my-[70px]">
          <Header />
        </section>

        <section className="">{children}</section>

        <section>
          <Footer />
        </section>
      </body>
    </html>
  );
}
