import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kiinew",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen h-screen`}>
        <section className="flex justify-center items-center">
          <Header />
        </section>
        <section className="px-[5%] py-[5%]">{children}</section>
      </body>
    </html>
  );
}
